### ISSUE TITLE
Fix pkgdown config for reference

### ISSUE THREAD

**Issue by maelle** [timtrice/hurricanes#198]
Some topics are missing from the configuration file.

```r
 Error in check_missing_topics(rows, pkg) : 
  All topics must be included in reference index
• Missing topics: extract_storm_links, fstadv, serial_from_basin_id, serial_from_name
ℹ Either add to _pkgdown.yml or use @keywords internal
```

Note that for topics you do not want to include in the index you can create an "internal" section https://pkgdown.r-lib.org/reference/build_reference.html?q=internal#missing-topics

To check all topics are listed, after editing the configuration file you can run `pkgdown::check_pkgdown()`.

**Comment by elinw** [comment]
Should work now.

**Comment by maelle** [comment]
Thanks! Note at least one vignette still fails: https://github.com/r-universe/ropensci/actions/runs/3212714599/jobs/5251824316
